version: '3.8'
services:
  focalboard:
    image: mattermost/focalboard
    restart: "always"
    container_name: focalboard
    volumes:
      - focalboard-data:/data
    networks:
      - default
    #depends_on:
     # - db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.focalboard-secure.rule=Host(`focoboard.jimenozki.gq`)" # Cambiar por el dominio correcto
      - "traefik.http.routers.focalboard-secure.entrypoints=websecure"
      - "traefik.http.services.focalboard-secure.loadbalancer.server.port=8000"
      #- "traefik.http.routers.focalboard-secure.middlewares=user-auth@file"
      #- "traefik.http.routers.focalboard-secure.service=focalboard-secure"
volumes:
  focalboard-data:
networks:
  default:
    external: true
    name: core_proxy